export const EnvKeys = {
  DATABASE_URL: 'DATABASE_URL',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  ENABLE_SCHEDULER: 'ENABLE_SCHEDULER',
  LLM_BASE_URL: 'LLM_BASE_URL',
  LLM_API_KEY: 'LLM_API_KEY',
  LLM_MODEL: 'LLM_MODEL',
  LLM_PROVIDER: 'LLM_PROVIDER',
  SMTP_HOST: 'SMTP_HOST',
  SMTP_PORT: 'SMTP_PORT',
  SMTP_USER: 'SMTP_USER',
  SMTP_PASS: 'SMTP_PASS',
  EMAIL_FROM: 'EMAIL_FROM',
} as const;

export const EnvDefaults = {
  PORT: 3000,
  JWT_EXPIRES_IN: '24h',
} as const;
