export const PrismaErrorCodes = {
  CONNECTION_FAILED: 'P1001',
  DATABASE_TIMEOUT: 'P1002',
  OPERATIONS_TIMED_OUT: 'P1008',
  SERVER_CLOSED_CONNECTION: 'P1017',
  UNIQUE_VIOLATION: 'P2002',
  FOREIGN_KEY_VIOLATION: 'P2003',
  COLUMN_NOT_FOUND: 'P2022',
} as const;

export const DATABASE_UNAVAILABLE_PRISMA_CODES = [
  PrismaErrorCodes.CONNECTION_FAILED,
  PrismaErrorCodes.DATABASE_TIMEOUT,
  PrismaErrorCodes.OPERATIONS_TIMED_OUT,
  PrismaErrorCodes.SERVER_CLOSED_CONNECTION,
] as const;
